### ISSUE TITLE
Loading dialog won't disappear

### ISSUE THREAD

**Issue by radem205** [domoticz/domoticz-android#56] opened 2016-01-12 12:22 UTC
Hi,

Currently I'm using version 0.1.210 of the Domoticz app. Great app btw! 

When I launch the app the loading dialog appears. When the data is loaded, the dialog disappears, but reappears instantly and won't go away anymore. The only option is to kill the app and relaunch it. 

This problem occurs randomly.

**Comment by RoadXY** [comment] 2016-01-12 13:09
It's really hard to solve bugs if we're unable to reproduce them...

**Comment by galadril** [comment] 2016-01-12 13:11
App version 0.1.210, we're at this moment on 0.1.216.
Please check if this problem stil happens on the latest version.

**Comment by radem205** [comment] 2016-01-12 13:13
Hmm strange, I'm a beta tester, but there's no update available in Google Play store.

**Comment by galadril** [comment] 2016-01-12 13:14
Ah, 0.1.210 is alpha.. 
We're testing the latest things, please wait til the update is pushed to beta

**Comment by galadril** [comment] 2016-01-14 09:11
We don't use Loading dialog anymore in the latest beta, so im going to close this case

**Closed by galadril** 2016-01-14 09:11 UTC
Labels: bug
