### ISSUE TITLE
Switch contact issue

### ISSUE THREAD

**Issue by piokuc01** [domoticz/domoticz-android#193] opened 2016-02-14 08:12 UTC
Hi
I found bug with swithc contact. First is that when i have switch contact i can from app on and off button. But in web app i can not change status this switch. In app should not show button for switch contact , that should only show statsu OPEN/CLOSED and user can not change this status. It was change when contact is open or close.

Seceond issue is that info show on bootom page when switch is open and close. Show thta switch is ON and OFF. Now is info: "Turning switch On" and "Turning switch Off" but should be "Turning Switch open" and "Turning switch closed"

**Comment by RoadXY** [comment] 2016-02-14 11:27
Duplicate of #185

**Closed by RoadXY** 2016-02-14 11:27 UTC
Labels: duplicate
