### ISSUE TITLE
widget groups and scenes not OK

### ISSUE THREAD

**Issue by jewlsoft** [domoticz/domoticz-android#27] opened 2016-01-07 09:18 UTC
Widgets inconsistently.

Switches:
working fine

Groups:
The meaning is to add items (switches) in a group and start an ON/OFF action.
Not always all the items in the group have the same status so the widget displays status "Mixed".
Now I should have the possibility to switch ON **and** OFF, not only ON **or** OFF.
The widget should display 2 buttens...

Scenes:
Allmost the same meaning as by group except a scene is just a sequence off actions, so the button should display START or something similer.

**Comment by RoadXY** [comment] 2016-01-20 12:13
Closed as duplicate of #7

**Closed by RoadXY** 2016-01-20 12:13 UTC
Labels: bug, Widgets
