### ISSUE TITLE
thermostat setpoints 

### ISSUE THREAD

**Issue by btedeski** [domoticz/domoticz-android#48] opened 2016-01-09 07:01 UTC
thermostat set point heat on dashboard sets very strange numbers
Thermostat is a Trane TZEMT400BB32
works from Domoticz web on Raspberry but not android app

hitting + gives strange numbers does not just add 1 to current temp
162.5
325.4
678.6
36.0
97.7
5.0
47.9

etc

**Comment by RoadXY** [comment] 2016-01-09 11:22
Mark has done some great work on a new implementation

![download_20160109_122214](https://cloud.githubusercontent.com/assets/3482284/12215793/a7505a1c-b6cb-11e5-8aa8-65e7c86659eb.png)

**Comment by btedeski** [comment] 2016-01-09 16:52
Great, how do I get a copy of the new version

**Comment by RoadXY** [comment] 2016-01-09 23:15
Wait for it to become beta or build from code

**Comment by btedeski** [comment] 2016-01-11 04:08
Pulled the source, settings show that I am now running version 0.1.214
of android client
is that the current on the development-branch?
does not match any of the branch tags
still having issues with heat setpoint
right now set point shows 77.0
Hit the set button  the circle temperature control show maxed at 50
set it down to 25.0 and hit ok  heat set point now showing 76.1 
hit set button again control once again jumps to maxed at 50, hit ok
set point now 122.0
looks like set point on app not doing Fahrenheit on control.
also not doing Celsius correct  25 should be 77 not 76.1
Bill,

**Comment by remb0** [comment] 2016-01-11 06:47
works! but the slider don't (i think by design)
and can you swap + and -    
+ right
- left

**Comment by RoadXY** [comment] 2016-01-11 08:38
What's the problem with the slider then?

@btedeski Could be that Fahrenheit is not correct implemented.

**Comment by galadril** [comment] 2016-01-11 10:58
I've reworked the dialog for fahrenheit & celcius, can you please check if this would work better??
https://github.com/domoticz/domoticz-android/commit/1ce58b07b40e8bebc49da82ae4a7e990955604a2

Could you else give me view rights on your system?

**Comment by galadril** [comment] 2016-01-11 10:59
Why doesn't the slider works??

**Comment by btedeski** [comment] 2016-01-11 17:12
I think the slider works,  but is in C not F

**Comment by btedeski** [comment] 2016-01-11 17:14
send me an email that does not show up in github and I will send you
url/id/password

**Comment by btedeski** [comment] 2016-01-11 17:51
here is were I am at today,
just noticed that I had both the google play version of the app
and the version I build at home installed,  deleted both to be sure
that I am clean
pulled new update from github development, built, and installed
heat setpoint slider looks better,  looks like it really might be
showing F not C
goes up to 196.0 F not topping of at 50
used slider to set to 84.0 F, press ok,   set point not shows 183.2
real thermostat did not change still set at 72.0
used slider to set to 73.0 F,  set point shows 167.0
thermostat still set at 72.0 
used slider to set to 20.0 F set point shows as 68.0
thermostat still set at 72.0
also slider +- buttons inconsistent
+ - buttons increment/decrements by 2

if you hit + then - the - button increments
if you hit - then + the + button decrements
if you hit - + - + starting at 86.0 the values read as 84 82 84 82
expected 84 86 84 86
Might take a look at the code tonight

**Comment by galadril** [comment] 2016-01-12 08:27
@btedeski can you send me your system  info (url/username/password) via PM on the Domoticz forum?
Im galadril on the forum..

**Comment by btedeski** [comment] 2016-01-12 17:11
tried, but the forum rules do not permit new users to send PM
here is the info,  I will disable the view account when you are done
https://zwave.tedeski.com:8443
username     admin
password     puppyupper

**Comment by galadril** [comment] 2016-01-12 17:21
i can't browse to 'https://zwave.tedeski.com:8443', you can email me:
heinis.mark@gmail.com

**Comment by PiterEL** [comment] 2016-01-13 15:44
i update to latest version 0.1.217 and problem with set thermostat is still...

Example when i set point 5.0 and click OK, on screen show set point 5.5
And when again go to setup, first click on button "-" not set lower , set bigger. Second click set lower point.

**Comment by Jaap-Jan** [comment] 2016-01-15 10:47
I think the setpoint is set 0.5 C too low. I'm busy with implementing setting zone temperatures in Evohome and if the setpoint is set to 10 C in the constructor call to `TemperatureDialog`, the dialog opens with the current temperature set to 9.5 C.

**Comment by galadril** [comment] 2016-02-02 10:40
Think bryan117 fixed this issue.
Close??

**Comment by btedeski** [comment] 2016-02-02 13:39
I will try it tonight


-------- Original message --------

**Comment by btedeski** [comment] 2016-02-02 17:17
what branch of the android app is the fix in,  looks like master not
building for me



:app:lint FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:lint'.
> Lint found errors in the project; aborting build.
  
  Fix the issues identified by lint, or add the following to your build
script to proceed with errors:
  ...
  android {
      lintOptions {
          abortOnError false
      }
  }
  ...

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or
--debug option to get more log output.

**Comment by Jaap-Jan** [comment] 2016-02-02 17:22
The fix is merged into the alpha-development branch, so that's the one you need to build.

**Comment by btedeski** [comment] 2016-02-03 18:12
I build the alpha train this morning,
the set heat function looks good on the android app, but still may be
an issue on the server side,
android app showed heat point set to 72,
changed it to 73 in android app,
android app then showed set point as 168.8
domoticz server also now shows set point as 168.8
changing the heat set point in the server GUI does not work
so looks like android app working (as best I can tell) but server side
needs work,
going to build the server from source and give it a try

**Comment by galadril** [comment] 2016-02-04 09:49
Thanks for testing, hope you find something!! :+1:

**Closed** 2016-02-17 15:37 UTC
Labels: bug, Needs testing
